services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=your-secret-key-change-this
      - ENABLE_OLLAMA_API=false
      - ENABLE_OPENAI_API=true
      - OPENAI_API_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=
      - ENABLE_ANTHROPIC_API=true
      - ANTHROPIC_API_BASE_URL=https://api.anthropic.com
      - ANTHROPIC_API_KEY=
      - ENABLE_CUSTOM_API=true
      - PORT=8080
      - ENABLE_WEBSOCKET_SUPPORT=true
      - WEBSOCKET_MANAGER=memory
      - WEBUI_URL=https://openwebui.australianteamasters.com.au
      # Force longer timeouts to prevent Bad Gateway
      - AIOHTTP_CLIENT_TIMEOUT=0
      - REQUEST_TIMEOUT=0
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      
      # Use Dokploy's auto-generated service names to avoid conflicts
      # Just add the essential streaming/timeout fixes
      - traefik.http.services.open-webui.loadbalancer.responseforwarding.flushinterval=1ms
      - traefik.http.services.open-webui.loadbalancer.passhostheader=true

volumes:
  open-webui: {}

networks:
  dokploy-network:
    external: true
